### ISSUE TITLE
Redirection / SSL issues

### ISSUE THREAD

**Issue by cwgoes** [tbabej/tbabej.github.io#1]
Interesting post on Yubikey session authentication - unfortunately, I cannot read it in Jekyll's nicely formatted HTML output, as your custom domain doesn't appear to be configured quite correctly with GitHub Pages.

```bash
> curl https://tbabej.com/ 
curl: (51) SSL: no alternative certificate subject name matches target host name 'tbabej.com'
```

```bash
> curl -k https://tbabej.com/ 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

```bash
> curl -k https://tbabej.github.io
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by tbabej** [comment]
Enforcing https causes this loop to happen if we're hosting on the apex domain directly. Letting users access over http or https for the time being - until I move to non-github based hosting.

Good job with finding the site before being advertised and hitting the one-day window when it was down!
